[package]
name = "conmon-common"
# Version listed below is also used by .packit.sh
version = "0.7.3"
edition = "2024"

[dependencies]
capnp = "0.21.7"

[build-dependencies]
capnp = { version = "0.21.7", default-features = false }
capnpc = { version = "0.21.4", default-features = false }
