[package]
name = "conmon-common"
# Version listed below is also used by .packit.sh
version = "0.5.1"
edition = "2021"

[dependencies]
capnp = "0.16.1"

[build-dependencies]
capnp = "0.16.1"
capnpc = "0.16.5"
