[package]
name = "conmon-common"
# Version listed below is also used by .packit.sh
version = "0.7.1"
edition = "2024"

[dependencies]
capnp = "0.21.5"

[build-dependencies]
capnp = { version = "0.21.5", default-features = false }
capnpc = { version = "0.21.4", default-features = false }
