[package]
name = "conmonrs-cli"
version = "0.1.0"
edition = "2018"

[dependencies]
async-io = "1.7.0"
async-net = "1.7.0"
capnp = "0.14.8"
capnp-rpc = "0.14.1"
conmon-common = { path = "../common" }
futures = "0.3.23"
log = { version = "0.4.17", features = ["serde", "std"] }
serde = { version = "1.0.143", features = ["derive"] }
tokio = { version = "1.20.1", features = ["fs", "macros", "net", "process", "rt", "signal", "time"] }
