[package]
name = "conmonrs-cli"
version = "0.6.4"
edition = "2021"

[dependencies]
capnp = "0.19.6"
capnp-rpc = "0.19.2"
conmon-common = { path = "../common" }
futures = "0.3.30"
log = { version = "0.4.22", features = ["serde", "std"] }
serde = { version = "1.0.204", features = ["derive"] }
tokio = { version = "1.38.1", features = ["fs", "macros", "net", "process", "rt", "signal", "time"] }
tokio-util = { version = "0.7.11", features = ["compat"] }
