[package]
name = "conmonrs-cli"
version = "0.7.1"
edition = "2024"

[dependencies]
capnp = { version = "0.21.5", default-features = false }
capnp-rpc = { version = "0.21.0", default-features = false }
conmon-common = { path = "../common" }
futures = { version = "0.3.31", default-features = false }
log = { version = "0.4.28", default-features = false, features = ["serde", "std"] }
serde = { version = "1.0.223", default-features = false, features = ["derive"] }
tokio = { version = "1.47.1", default-features = false, features = ["fs", "macros", "net", "process", "rt", "signal", "time"] }
tokio-util = { version = "0.7.16", default-features = false, features = ["compat"] }
