[package]
name = "conmonrs-cli"
version = "0.5.0"
edition = "2018"

[dependencies]
capnp = "0.14.10"
capnp-rpc = "0.14.1"
conmon-common = { path = "../common" }
futures = "0.3.26"
log = { version = "0.4.17", features = ["serde", "std"] }
serde = { version = "1.0.152", features = ["derive"] }
tokio = { version = "1.25.0", features = ["fs", "macros", "net", "process", "rt", "signal", "time"] }
tokio-util = { version = "0.7.6", features = ["compat"] }
